-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Apr 15, 2021 at 06:51 PM
-- Server version: 5.7.31
-- PHP Version: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_roku`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_kidsmovies`
--

DROP TABLE IF EXISTS `tbl_kidsmovies`;
CREATE TABLE IF NOT EXISTS `tbl_kidsmovies` (
  `kidsmovies_id` int(11) NOT NULL AUTO_INCREMENT,
  `kidsmovies_cover` varchar(50) NOT NULL,
  `kidsmovies_title` varchar(100) NOT NULL,
  `kidsmovies_year` varchar(5) NOT NULL,
  `kidsmovies_runtime` varchar(10) NOT NULL,
  `kidsmovies_storyline` text NOT NULL,
  `kidsmovies_video` varchar(50) NOT NULL,
  PRIMARY KEY (`kidsmovies_id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_kidsmovies`
--

INSERT INTO `tbl_kidsmovies` (`kidsmovies_id`, `kidsmovies_cover`, `kidsmovies_title`, `kidsmovies_year`, `kidsmovies_runtime`, `kidsmovies_storyline`, `kidsmovies_video`) VALUES
(1, 'starWars_aNewHope.png', 'Star Wars', '1977', '121m', 'Amid a galactic civil war, Rebel Alliance spies have stolen plans to the Galactic Empire\'s Death Star, a massive space station capable of destroying an entire planet. Imperial Senator Princess Leia of Alderaan, secretly one of the Rebellion\'s leaders, has obtained its schematics, but her starship is intercepted by an Imperial Star Destroyer under the command of the ruthless Darth Vader. Before she is captured, Leia hides the plans in the memory of astromech droid R2-D2, who flees in an escape pod to the desert planet Tatooine accompanied by protocol droid C-3PO.', 'starWars_aNewHope.mp4'),
(2, 'backToTheFuture.png', 'Back To The Future', '1985', '116m', 'In 1985, Marty McFly is a typical teenager living in Hill Valley, California. At home, Marty\'s cowardly father George is bullied by his supervisor, Biff Tannen. His mother Lorraine is an overweight, depressed alcoholic, and his older siblings are professional and social failures. An aspiring musician, Marty\'s band is rejected for a music contest. He confides in his girlfriend Jennifer Parker about fears of becoming like his parents, despite his ambitions.', 'backToTheFuture.mp4'),
(3, 'raidersOfTheLostArk.png', 'Raiders Of The Lost Ark', '1981', '115m', 'In 1936, American archaeologist Indiana Jones recovers a golden idol from a booby-trapped Peruvian temple. Cornered by rival archaeologist René Belloq, the idol is stolen and Jones escapes in a waiting seaplane. After returning to America, Jones is approached by two Army Intelligence agents. They reveal Nazis are excavating Tanis, and one of their telegrams mentions Jones\'s old mentor Abner Ravenwood. Jones deduces the Nazis are searching for the Ark of the Covenant, which Adolf Hitler believes will make their army invincible. The agents recruit Jones to recover the Ark first.', 'raidersOfTheLostArk.mp4');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_kidsmusic`
--

DROP TABLE IF EXISTS `tbl_kidsmusic`;
CREATE TABLE IF NOT EXISTS `tbl_kidsmusic` (
  `kidsmusic_id` int(11) NOT NULL AUTO_INCREMENT,
  `kidsmusic_cover` varchar(50) NOT NULL,
  `kidsmusic_artist` varchar(50) NOT NULL,
  `kidsmusic_title` varchar(100) NOT NULL,
  `kidsmusic_year` varchar(5) NOT NULL,
  `kidsmusic_desc` text NOT NULL,
  `kidsmusic_audio` varchar(100) NOT NULL,
  PRIMARY KEY (`kidsmusic_id`)
) ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_kidsmusic`
--

INSERT INTO `tbl_kidsmusic` (`kidsmusic_id`, `kidsmusic_cover`, `kidsmusic_artist`, `kidsmusic_title`, `kidsmusic_year`, `kidsmusic_desc`, `kidsmusic_audio`) VALUES
(1, 'abbeyRoad.png', 'The Beatles', 'Abbey Road', '1969', 'Abbey Road is the eleventh studio album by the English rock band the Beatles, released on 26 September 1969 by Apple Records. Named after the location of EMI Studios in London, the cover features the group walking across the street\'s zebra crossing, an image that became one of the most famous and imitated in popular music. The album\'s initially mixed reviews were contrasted by its immediate commercial success, topping record charts in the UK and US. The lead single \"Something\" / \"Come Together\" was released in October and topped the US charts.', 'theBeatles_abbeyRoad_comeTogether.mp3'),
(5, 'buddyHolly_buddyHolly.png', 'Buddy Holly', 'Buddy Holly', '1958', 'Buddy Holly is the debut studio album by Buddy Holly. It was released by Coral Records on February 20, 1958. The album collects Holly\'s four hit singles released on the Coral label; \"Words of Love\", \"Peggy Sue\", \"I\'m Gonna Love You Too\", and \"Rave On!\". The backing group was Buddy Holly\'s band, the Crickets.', 'buddyHolly_buddyHolly_i\'mGonnaLoveYouToo.mp3'),
(8, 'daftPunk_homework.png', 'Daft Punk', 'Homework', '1997', 'Homework is the debut studio album by the French electronic music duo Daft Punk, released on 20 January 1997 by Virgin Records and Soma Quality Recordings. The duo produced the tracks without plans to release an album. After working on projects that were intended to be separate singles over five months, they considered the material good enough for an album.', 'daftPunk_homework_daFunk.mp3'),
(14, 'journey_escape.png', 'Journey', 'Escape', '1981', 'Escape (stylized as E5C4P3 on the album cover) is the seventh studio album by American rock band Journey, released in 1981. It topped the American Billboard 200 chart[1] and features four hit Billboard Hot 100 singles – \"Don\'t Stop Believin\'\" (#9), \"Who\'s Crying Now\" (#4), \"Still They Ride\" (#19) and \"Open Arms\" (#2)[2] – plus rock radio staple \"Stone in Love.\" It was certified 9x platinum by the RIAA[3] and sold over twelve million copies worldwide, making it the band\'s most successful studio album and second most successful album overall behind Greatest Hits.', 'journey_escape_don\'tStopBelievin\'.mp3'),
(16, 'michaelJackson_thriller.png', 'Michael Jackson', 'Thriller', '1982', 'Thriller is the sixth studio album by American singer Michael Jackson, released on November 30, 1982, by Epic Records. Reunited with Off the Wall producer Quincy Jones, Jackson was inspired to create an album where \"every song was a killer\". With the ongoing backlash against disco, Jackson moved in a new musical direction, incorporating pop, post-disco, rock and funk. Thriller foreshadows the contradictory themes of Jackson\'s personal life, as he began using a motif of paranoia and darker themes. The album features a single guest appearance, with Paul McCartney becoming the first artist to be featured on one of Jackson\'s albums. Recording took place from April to November 1982 at Westlake Recording Studios in Los Angeles, with a production budget of $750,000.', 'michaelJackson_thriller_thriller.mp3'),
(26, 'theBeachBoys_petSounds.png', 'The Beach Boys', 'Pet Sounds', '1966', 'Pet Sounds is the 11th studio album by the American rock band the Beach Boys, released May 16, 1966 on Capitol Records. It was initially met with a lukewarm critical and commercial response in the United States, peaking at number 10 on Billboard Top LPs chart, lower than the band\'s preceding albums. In the United Kingdom, the album was favorably received by critics and peaked at number 2 in the UK Top 40 Albums Chart, remaining in the top ten for six months. Promoted there as \"the most progressive pop album ever\", Pet Sounds attracted recognition for its ambitious production, sophisticated music, and emotional lyric content. It is considered to be among the most influential albums in music history.[1]', 'theBeachBoys_petSounds_godOnlyKnows.mp3'),
(27, 'theBeatles_sgt.Peppers.png', 'The Beatles', 'Sgt.Pepper\'s Lonely Hearts Club Band', '1967', 'Sgt. Pepper\'s Lonely Hearts Club Band is the eighth studio album by the English rock band the Beatles. Released on 26 May 1967,[nb 1] it spent 27 weeks at number one on the Record Retailer chart in the United Kingdom and 15 weeks at number one on the Billboard Top LPs chart in the United States. It was lauded by critics for its innovations in songwriting, production and graphic design, for bridging a cultural divide between popular music and high art, and for reflecting the interests of contemporary youth and the counterculture. Its release was a defining moment in 1960s pop culture, heralding the Summer of Love, while the album\'s reception achieved full cultural legitimisation for pop music and recognition for the medium as a genuine art form.', 'theBeatles_sgt.Peppers_aDayInTheLife.mp3'),
(29, 'theJacksonFive_iWantYouBack.png', 'The Jackson Five', 'I Want You Back', '1969', '\"I Want You Back\" is the first national single by the Jackson 5.[3] It was released by Motown on October 7, 1969, and became the first number-one hit for the band on January 31, 1970.[4] It was performed on the band\'s first television appearances, on October 18, 1969 on Diana Ross\'s The Hollywood Palace and on their milestone performance on December 14, 1969 on The Ed Sullivan Show.[4]', 'theJacksonFive_iWantYouBack.mp3');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_kidstv`
--

DROP TABLE IF EXISTS `tbl_kidstv`;
CREATE TABLE IF NOT EXISTS `tbl_kidstv` (
  `kidstv_id` int(11) NOT NULL AUTO_INCREMENT,
  `kidstv_cover` varchar(50) NOT NULL,
  `kidstv_title` varchar(50) NOT NULL,
  `kidstv_year` varchar(12) NOT NULL,
  `kidstv_storyline` text NOT NULL,
  `kidstv_video` varchar(50) NOT NULL,
  PRIMARY KEY (`kidstv_id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_kidstv`
--

INSERT INTO `tbl_kidstv` (`kidstv_id`, `kidstv_cover`, `kidstv_title`, `kidstv_year`, `kidstv_storyline`, `kidstv_video`) VALUES
(1, 'andyGriffithShow.png', 'The Andy Griffith Show', '1960', 'The series plot revolves around Sheriff Andy Taylor (Andy Griffith) and his life in sleepy, slow-paced fictional Mayberry, North Carolina. Sheriff Taylor\'s level-headed approach to law enforcement makes him the scourge of local moonshiners and out-of-town criminals, while his abilities to settle community problems with common-sense advice, mediation, and conciliation make him popular with his fellow citizens. His professional life, however, is complicated by the repeated gaffes of his inept deputy, Barney Fife (Don Knotts). Barney is Andy\'s cousin, but that is only mentioned in a few early episodes. Andy socializes with male friends in the Main Street barbershop and dates various ladies until a schoolteacher becomes his steady interest in season three. At home, Andy enjoys fishing trips with his son, Opie (Ronny Howard), and quiet evenings on the front porch with his maiden aunt and housekeeper, Aunt Bee (Frances Bavier). Opie tests his father\'s parenting skills season after season, and Aunt Bee\'s ill-considered romances and adventures cause her nephew concern.[citation needed] Andy\'s friends and neighbors include, at various times, barber Floyd Lawson (Howard McNear; Walter Baldwin portrayed the role in the 1960 episode \"Stranger in Town\"), service station attendants and cousins Gomer Pyle (Jim Nabors) and Goober Pyle (George Lindsey), and local drunkard Otis Campbell (Hal Smith). There were two mayors: Mayor Pike (Richard Damon Elliott), who was more relaxed and often indecisive, and Mayor Roy Stoner (Parley Baer) who had a more assertive personality. On the distaff side, townswoman Clara Edwards (Hope Summers), Barney\'s sweetheart Thelma Lou (Betty Lynn) and Andy\'s schoolteacher sweetheart Helen Crump (Aneta Corsaut) become semi-regulars. Ellie Walker (Elinor Donahue) is Andy\'s girlfriend in the first season, while Peggy McMillan (Joanna Moore) is a nurse who becomes his girlfriend in season 3. Ernest T. Bass made his first appearance in Episode #94 (\"Mountain Wedding\") and four later episodes. The actor who portrayed him, Howard Morris, also appeared as George, the television repairman, in Episode #140 (\"Andy and Helen Have Their Day\") and in two, uncredited voice roles as Leonard Blush and a radio announcer. ', 'andyGriffith.mp4'),
(4, 'freshPrince.png', 'The Fresh Prince Of Bel-Air', '1990', 'The theme song and opening sequence set the premise of the show. Will Smith is a street-smart teenager, West Philadelphia \"born and raised\". While playing street basketball, Will misses a shot and the ball hits a group of gang members, causing a confrontation that frightens his mother, who sends him to live with his wealthy aunt and uncle in the opulent neighborhood of Bel Air, Los Angeles.', 'freshPrince.mp4'),
(9, 'iLoveLucy.png', 'I Love Lucy', '1951', 'Originally set in an apartment building in New York City, I Love Lucy centers on Lucy Ricardo (Lucille Ball) and her singer/bandleader husband Ricky Ricardo (Desi Arnaz), along with their best friends and landlords Fred Mertz (William Frawley) and Ethel Mertz (Vivian Vance). During the second season, Lucy and Ricky have a son named Ricky Ricardo Jr. (\"Little Ricky\"), whose birth was timed to coincide with Ball\'s real-life birth of her son Desi Arnaz Jr.[10]', 'iLoveLucy.mp4'),
(11, 'leaveBeaver.png', 'Leave It To Beaver', '1957', 'In 1957, the radio, film and television writers Joe Connelly and Bob Mosher developed a concept for a TV show about childhood and family life featuring a fictional suburban couple and their children. Unlike The Adventures of Ozzie & Harriet, Father Knows Best and other sitcoms and domestic comedies of the era, the show would not focus on the parents, but rather on their children, with the series being told from the kids\' point of view.[5] Working titles during the show\'s gestation period included It\'s a Small World[2] and Wally and the Beaver. The pilot aired April 23, 1957, as \"It\'s a Small World\" on the anthology series Heinz Studio 57.[3]', 'leaveBeaver.mp4'),
(12, 'looneyTunes.png', 'Looney Tunes', '1930', 'More popular Looney Tunes characters were created (most of which first appeared in Merrie Melodies cartoons) such as Tweety (debuted in 1942\'s A Tale of Two Kitties), Sylvester (debuted in 1945\'s Life with Feathers), Yosemite Sam (debuted in 1945\'s Hare Trigger), Pepé Le Pew (debuted in 1945\'s Odor-able Kitty), Foghorn Leghorn (debuted in 1946\'s Walky Talky Hawky), Marvin the Martian (debuted in 1948\'s Haredevil Hare), Wile E. Coyote and the Road Runner (debuted in 1949\'s Fast and Furry-ous), Granny (debuted in 1950\'s Canary Row), Speedy Gonzales (debuted in 1953\'s Cat Tails for Two), Witch Hazel (debuted in 1954\'s Bewitched Bunny), and the Tasmanian Devil (debuted in 1954\'s Devil May Hare).', 'looneyTunes.mp4'),
(18, 'starTrek.png', 'Star Trek', '1968', 'The series was produced from September 1966 to December 1967 by Norway Productions and Desilu Productions, and by Paramount Television from January 1968 to June 1969. Star Trek aired on NBC from September 8, 1966, to June 3, 1969,[6] and was actually seen first on September 6, 1966, on Canada\'s CTV network.[7] Star Trek\'s Nielsen ratings while on NBC were low, and the network cancelled it after three seasons and 79 episodes. Several years later, the series became a hit in broadcast syndication, remaining so throughout the 1970s, achieving cult classic status and a developing influence on popular culture. Star Trek eventually spawned a franchise, consisting of eight television series, 13 feature films, and numerous books, games, and toys, and is now widely considered one of the most popular and influential television series of all time.[8] The series contains significant elements of Space Western, as described by Roddenberry and the general audience.[9]', 'starTrek.mp4'),
(19, 'theFlintstones.png', 'The Flintstones', '1960', 'The show is set in a comical version of the Stone Age, but has added features and technologies that resemble mid-20th-century suburban America. The plots deliberately resemble the sitcoms of the era, with the caveman Flintstone and Rubble families getting into minor conflicts characteristic of modern life.[7] The show is set in the Stone Age town of Bedrock (pop. 2,500). Dinosaurs and other prehistoric creatures are portrayed to co-exist during the time of cavemen, saber-toothed cats, and woolly mammoths.', 'theFlintstones.mp4'),
(20, 'twilight.png', 'The Twilight Zone', '1959', 'The Twilight Zone is an American media franchise based on the anthology television series created by Rod Serling. The episodes are in various genres, including fantasy, science fiction, absurdism, dystopian fiction, suspense, horror, supernatural drama, black comedy, and psychological thriller, often concluding with a macabre or unexpected twist, and usually with a moral. A popular and critical success, it introduced many Americans to common science fiction and fantasy tropes. The first series, shot entirely in black and white, ran on CBS for five seasons from 1959 to 1964.', 'twilightZone.mp4');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_movies`
--

DROP TABLE IF EXISTS `tbl_movies`;
CREATE TABLE IF NOT EXISTS `tbl_movies` (
  `movies_id` int(11) NOT NULL AUTO_INCREMENT,
  `movies_cover` varchar(50) NOT NULL,
  `movies_title` varchar(50) NOT NULL,
  `movies_year` varchar(4) NOT NULL,
  `movies_runtime` varchar(10) NOT NULL,
  `movies_storyline` text NOT NULL,
  `movies_video` varchar(50) NOT NULL,
  PRIMARY KEY (`movies_id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_movies`
--

INSERT INTO `tbl_movies` (`movies_id`, `movies_cover`, `movies_title`, `movies_year`, `movies_runtime`, `movies_storyline`, `movies_video`) VALUES
(1, 'alien.png', 'Alien', '1979', '117m', 'The commercial space tug Nostromo is returning to Earth with a seven-member crew in stasis: Captain Dallas, Executive Officer Kane, Warrant Officer Ripley, Navigator Lambert, Science Officer Ash, and two engineers, Parker and Brett. Detecting a transmission, the ship\'s computer, Mother, awakens the crew. Per company policy requiring any potential distress signal be investigated, they land on the moon despite Parker\'s protests, sustaining damage from its atmosphere and rocky landscape in the process. The engineers stay on board to effect repairs while Dallas, Kane, and Lambert head out to investigate. They discover the signal originates from a derelict alien ship and enter it, losing communication with the Nostromo. Ripley deciphers part of the transmission, determining it to be a warning, but cannot relay this information to those on the derelict ship.', 'alien.mp4'),
(2, 'backToTheFuture.png', 'Back To The Future', '1985', '116m', 'In 1985, Marty McFly is a typical teenager living in Hill Valley, California. At home, Marty\'s cowardly father George is bullied by his supervisor, Biff Tannen. His mother Lorraine is an overweight, depressed alcoholic, and his older siblings are professional and social failures. An aspiring musician, Marty\'s band is rejected for a music contest. He confides in his girlfriend Jennifer Parker about fears of becoming like his parents, despite his ambitions.', 'backToTheFuture.mp4'),
(3, 'bladeRunner.png', 'Blade Runner', '1982', '117m', 'In 2019 Los Angeles, former policeman Rick Deckard is detained by Officer Gaff, and brought to his former supervisor, Bryant. Deckard, whose job as a \"blade runner\" was to track down bioengineered humanoids known as replicants and terminally \"retire\" them, is informed that four replicants are on Earth illegally. Deckard begins to leave, but Bryant ambiguously threatens him and Deckard stays. The two watch a video of a blade runner named Holden administering the Voight-Kampff test, which is designed to distinguish replicants from humans based on their emotional response to questions. The test subject, Leon, shoots Holden on the second question. Bryant wants Deckard to retire Leon and three other Nexus-6 replicants: Roy Batty, Zhora, and Pris.', 'bladeRunner.mp4'),
(4, 'dr.StrangeLove.png', 'Dr. Strangelove', '1964', '94m', 'United States Air Force Brigadier General Jack D. Ripper is commander of Burpelson Air Force Base, which houses the 843rd Bomb Wing, flying B-52 bombers armed with hydrogen bombs. The planes are now on airborne alert two hours from their targets inside the USSR.', 'dr.StrangeLove.mp4'),
(5, 'fightClub.png', 'Fight Club', '1999', '139m', 'The Narrator, an automobile recall specialist, is unfulfilled by his job and possessions and suffers from chronic insomnia. To cure this, he attends support groups, posing as a sufferer of diseases. His bliss is disturbed when another impostor, Marla Singer, begins attending the same groups. The two agree to split which groups they attend.', 'fightClub.mp4'),
(6, 'jaws.png', 'Jaws', '1975', '124m', 'During a beach party at dusk on Amity Island, a young woman, Chrissie Watkins, goes skinny dipping in the ocean. While treading water, she is violently pulled under. The next day, her partial remains are found on shore. The medical examiner\'s conclusion that the death was due to a shark attack leads police chief Martin Brody to close the beaches. Mayor Larry Vaughn persuades him to reverse his decision, fearing that the town\'s summer economy will be ruined and points out that the town has never had trouble with sharks. The coroner tentatively concurs with the mayor\'s theory that Chrissie was killed in a boating accident. Brody reluctantly accepts their conclusion until the shark kills a young boy, Alex Kintner, in full view of a crowded beach. A bounty is placed on the shark, causing an amateur shark-hunting frenzy, and local professional shark fisherman Quint offers to catch and kill it for $10,000. Meanwhile, consulting oceanographer Matt Hooper examines Chrissie\'s remains, and confirms her death was caused by a shark—an unusually large one.', 'jaws.mp4'),
(7, 'lawrenceOfArabia.png', 'Lawrence Of Arabia', '1962', '227m', 'The story then moves back to the First World War. Lawrence is a misfit British Army lieutenant who is notable for his insolence and education. Over the objections of General Murray, Mr. Dryden of the Arab Bureau sends him to assess the prospects of Prince Faisal in his revolt against the Turks. On the journey, his Bedouin guide, Tafas, is killed by Sherif Ali for drinking from his well without permission. Lawrence later meets Colonel Brighton, who orders him to keep quiet, make his assessment, and leave. Lawrence ignores Brighton\'s orders when he meets Faisal; his outspokenness piques the prince\'s interest.', 'lawrenceOfArabia.mp4'),
(8, 'psyco.png', 'Psycho', '1960', '109m', 'During a lunchtime tryst in a Phoenix, Arizona, hotel, real-estate secretary Marion Crane and her boyfriend, Sam Loomis, discuss how they cannot afford to get married because of Sam\'s debts. After lunch, Marion returns to work where a client leaves a $40,000 cash payment on a property. Marion\'s boss asks her to deposit the money in the bank and allows her to leave early after she complains of a headache. Once home, she decides to steal the money and drive to Sam\'s home in Fairvale, California. En route to Fairvale, Marion stops her car on the side of the road and falls asleep. She is awakened the next morning by a California Highway Patrol officer. Suspicious of her nervous behavior, the officer follows her. Marion stops at a Bakersfield automobile dealership and trades in her car, which has Arizona license plates, for another car with California plates. The officer eyes her suspiciously as she drives away.', 'psyco.mp4'),
(9, 'pulpFiction.png', 'Pulp Fiction', '1994', '154m', 'Hitmen Jules Winnfield and Vincent Vega arrive at an apartment to retrieve a briefcase for their boss, gangster Marsellus Wallace, from a business partner, Brett. After Vincent checks the contents of the briefcase, Jules shoots one of Brett\'s associates, then declaims a passage from the Bible before he and Vincent kill Brett for trying to double-cross Marsellus. They take the briefcase to Marsellus, but they have to wait while he bribes boxer Butch Coolidge to take a dive in his upcoming match.', 'pulpFiction.mp4'),
(10, 'raidersOfTheLostArk.png', 'Raiders Of The Lost Ark', '1981', '115m', 'In 1936, American archaeologist Indiana Jones recovers a golden idol from a booby-trapped Peruvian temple. Cornered by rival archaeologist René Belloq, the idol is stolen and Jones escapes in a waiting seaplane. After returning to America, Jones is approached by two Army Intelligence agents. They reveal Nazis are excavating Tanis, and one of their telegrams mentions Jones\'s old mentor Abner Ravenwood. Jones deduces the Nazis are searching for the Ark of the Covenant, which Adolf Hitler believes will make their army invincible. The agents recruit Jones to recover the Ark first.', 'raidersOfTheLostArk.mp4'),
(11, 'silenceOfTheLambs.png', 'Silence Of The Lambs', '1991', '118m', 'In 1990, Clarice Starling is pulled from her FBI training at the Quantico, Virginia FBI Academy by Jack Crawford of the Bureau\'s Behavioral Science Unit. He assigns her to interview Hannibal Lecter, a former psychiatrist and incarcerated cannibalistic serial killer. Lecter\'s insight could prove useful in the pursuit of a serial killer nicknamed \"Buffalo Bill\", who kills young women and removes their skin from their bodies.', 'silenceOfTheLambs.mp4'),
(12, 'stalag17.png', 'Stalag 17', '1953', '120m', 'Stalag 17 begins on \"the longest night of the year\" in December 1944 in a Luftwaffe prisoner-of-war camp somewhere along the Danube River. The story is narrated by Clarence Harvey \"Cookie\" Cook. The camp holds Poles, Czechs, Russian women and, in the American compound, 640 sergeants from bomber crews, gunners, radiomen, and flight engineers.', 'stalag17.mp4'),
(13, 'starWars_aNewHope.png', 'Star Wars', '1977', '121m', 'Amid a galactic civil war, Rebel Alliance spies have stolen plans to the Galactic Empire\'s Death Star, a massive space station capable of destroying an entire planet. Imperial Senator Princess Leia of Alderaan, secretly one of the Rebellion\'s leaders, has obtained its schematics, but her starship is intercepted by an Imperial Star Destroyer under the command of the ruthless Darth Vader. Before she is captured, Leia hides the plans in the memory of astromech droid R2-D2, who flees in an escape pod to the desert planet Tatooine accompanied by protocol droid C-3PO.', 'starWars_aNewHope.mp4'),
(14, 'sunsetBoulevard.png', 'Sunset Boulevard', '1950', '110m', 'At a mansion on Sunset Boulevard, a group of police officers and photographers discover the body of Joe Gillis, floating face down in the swimming pool. In a flashback, Joe relates the events leading to his death.', 'sunsetBoulevard.mp4'),
(15, 'taxiDriver.png', 'Taxi Driver', '1976', '114m', 'Travis Bickle is a 26-year-old honorably discharged U.S. Marine and Vietnam War veteran suffering from post-traumatic stress disorder and living in isolation in New York City. Travis takes a job as a night shift taxi driver to cope with his chronic insomnia. He frequents the porn theaters on 42nd Street and keeps a diary in which he consciously attempts to include aphorisms, such as \"you\'re only as healthy as you feel.\"', 'taxiDriver.mp4'),
(16, 'theBridgeOnTheRiverKwai.png', 'The Bridge On The River Kwai', '1957', '161m', 'In early 1943, British POWs arrive at a Japanese prison camp in Burma, led by Colonel Nicholson. One of the other prisoners he meets is Commander Shears of the U.S. Navy, who describes the horrific conditions. Nicholson forbids any escape attempts because they were ordered by headquarters to surrender, and escapes could be seen as defiance of orders. Dense jungle surrounding the camp renders escape virtually impossible. Colonel Saito, the camp commandant, informs the new prisoners they will all work, even officers, on the construction of a railway bridge over the River Kwai that will connect Bangkok and Rangoon. Nicholson objects, informing Saito the Geneva Conventions exempts officers from manual labour. After the enlisted men are marched to the bridge site, Saito threatens to have the officers shot, until Major Clipton, the British medical officer, warns Saito there are too many witnesses for him to get away with murder. Saito leaves the officers standing all day in the intense heat. That evening, the officers are placed in a punishment hut, while Nicholson is locked in an iron box after getting beaten as punishment. Shears escapes and is wounded. He wanders into a Siamese village, is nursed back to health, and eventually arrives in the British colony of Ceylon.', 'theBridgeOnTheRiverKwai.mp4'),
(17, 'theGoodTheBadAndTheUgly.png', 'The Good The Bad And The Ugly', '1966', '177m', 'In 1862, during the American Civil War, a mercenary known as \"Angel Eyes\" interrogates former Confederate soldier Stevens, whom Angel Eyes is contracted to kill, about Jackson, a fugitive who stole a cache of Confederate gold. Learning Jackson\'s new alias \"Bill Carson\", Angel Eyes kills Stevens and the man who hired him, Baker, intending to find the gold himself. Bandit Tuco Ramirez is rescued from bounty hunters by a nameless drifter to whom Tuco refers as \"Blondie\", who delivers him to the local sheriff to collect his $2,000 bounty. As Tuco is about to be hanged, Blondie severs Tuco\'s noose by shooting it, and sets him free. The two escape on horseback and split the bounty. They repeat the process in other towns until Blondie grows weary of Tuco\'s complaints and strands him in the desert.', 'theGoodTheBadAndTheUgly.mp4'),
(18, 'theMatrix.png', 'The Matrix', '1999', '136m', 'Computer programmer Thomas Anderson, known by his hacking alias \"Neo\", feels something is wrong with the world and is puzzled by repeated online encounters with the phrase \"the Matrix\". Trinity contacts him and tells him a man named Morpheus has the answers he seeks. A team of Agents and police, led by Agent Smith, arrives at Neo\'s workplace searching for him. Though Morpheus attempts to guide Neo to safety via telephone, Neo is captured and coerced into helping the Agents locate Morpheus, whom they regard as a \"known terrorist\". Neo then wakes up from his dream. The same lady who met him at the bar arrives in a car to take him to Morpheus.', 'theMatrix.mp4'),
(19, 'theShining.png', 'The Shining', '1980', '146m', 'Writer Jack Torrance arrives at the remote Overlook Hotel in the Rocky Mountains to be interviewed for the position of winter caretaker. The hotel, which opened in 1909 and was built on the site of a Native American burial ground, closes during the snowed-in months. Once hired, Jack plans to use the hotel\'s solitude to write. Manager Stuart Ullman warns Jack about the hotel\'s reputation: a previous caretaker, Charles Grady, killed his family and himself. Jack is nevertheless impressed with the hotel and takes the job. In Boulder, Jack\'s son, Danny, has a premonition about the hotel, and Jack\'s wife, Wendy, tells a doctor about Danny\'s imaginary friend, Tony. She also reveals that Jack is a recovering alcoholic who once injured Danny in a drunken rage.', 'theShining.mp4'),
(20, 'vertigo.png', 'Vertigo', '1958', '128m', 'After a rooftop chase, where a fellow policeman falls to his death, San Francisco detective John \"Scottie\" Ferguson retires due to fear of heights and vertigo. Scottie tries to conquer his fear, but his ex-fiancée, underwear designer Marjorie \'Midge\' Wood, says that another severe emotional shock may be the only cure.', 'vertigo.mp4');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_music`
--

DROP TABLE IF EXISTS `tbl_music`;
CREATE TABLE IF NOT EXISTS `tbl_music` (
  `music_id` int(11) NOT NULL AUTO_INCREMENT,
  `music_cover` varchar(50) NOT NULL,
  `music_artist` varchar(50) NOT NULL,
  `music_title` varchar(100) NOT NULL,
  `music_year` varchar(5) NOT NULL,
  `music_desc` text NOT NULL,
  `music_audio` varchar(100) NOT NULL,
  PRIMARY KEY (`music_id`)
) ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_music`
--

INSERT INTO `tbl_music` (`music_id`, `music_cover`, `music_artist`, `music_title`, `music_year`, `music_desc`, `music_audio`) VALUES
(1, 'abbeyRoad.png', 'The Beatles', 'Abbey Road', '1969', 'Abbey Road is the eleventh studio album by the English rock band the Beatles, released on 26 September 1969 by Apple Records. Named after the location of EMI Studios in London, the cover features the group walking across the street\'s zebra crossing, an image that became one of the most famous and imitated in popular music. The album\'s initially mixed reviews were contrasted by its immediate commercial success, topping record charts in the UK and US. The lead single \"Something\" / \"Come Together\" was released in October and topped the US charts.', 'theBeatles_abbeyRoad_comeTogether.mp3'),
(2, 'acdc_backInBlack.png', 'ACDC', 'Back In Black', '1980', 'Back in Black is the seventh studio album by Australian rock band AC/DC. It was released on 25 July 1980 by Albert Productions and Atlantic Records. It is the band\'s first album to feature lead singer Brian Johnson, following the death of previous lead singer Bon Scott.', 'acdc_backInBlack_youShookMeAllNightLong.mp3'),
(3, 'bobDylan_highway61Revisited.png', 'Bob Dylan', 'Highway 61 Revisited', '1965', 'Highway 61 Revisited is the sixth studio album by American singer-songwriter Bob Dylan, released on August 30, 1965 by Columbia Records. Having until then recorded mostly acoustic music, Dylan used rock musicians as his backing band on every track of the album, except for the closing track, the 11-minute ballad \"Desolation Row\". Critics have focused on the innovative way Dylan combined driving, blues-based music with the subtlety of poetry to create songs that captured the political and cultural chaos of contemporary America. Author Michael Gray has argued that, in an important sense, the 1960s \"started\" with this album.[2]', 'bobDylan_highway61Revisited_likeARollingStone.mp3'),
(4, 'bonJovi_slipperyWhenWet.png', 'Bon Jovi', 'Slippery When Wet', '1986', 'Slippery When Wet is the third studio album by American glam metal band Bon Jovi. It was released on August 18, 1986 by Mercury Records in North America and Vertigo Records internationally. It was produced by Bruce Fairbairn, with recording sessions between January and July 1986 at Little Mountain Sound Studios in Vancouver, British Columbia, Canada. The album features many of Bon Jovi\'s best-known songs, including \"You Give Love a Bad Name\", \"Livin\' on a Prayer\", and \"Wanted Dead or Alive\".', 'bonJovi_slipperyWhenWet_livin\'OnAPrayer.mp3'),
(5, 'buddyHolly_buddyHolly.png', 'Buddy Holly', 'Buddy Holly', '1958', 'Buddy Holly is the debut studio album by Buddy Holly. It was released by Coral Records on February 20, 1958. The album collects Holly\'s four hit singles released on the Coral label; \"Words of Love\", \"Peggy Sue\", \"I\'m Gonna Love You Too\", and \"Rave On!\". The backing group was Buddy Holly\'s band, the Crickets.', 'buddyHolly_buddyHolly_i\'mGonnaLoveYouToo.mp3'),
(6, 'charlesMingus_mingusAhUm.png', 'Charles Mingus', 'Mingus Ah Um', '1959', 'Mingus Ah Um is a studio album by American jazz musician Charles Mingus, released in October 1959 by Columbia Records.[1][2] It was his first album recorded for Columbia. The cover features a painting by S. Neil Fujita.[6] The title is a corruption of an imaginary Latin declension. It is common for Latin students to memorize Latin adjectives by first saying the masculine nominative (usually ending in \"-us\"), then the feminine nominative (\"-a\"), and finally the neuter nominative singular (\"-um\")[7]--implying a transformation of his name, Mingus, Minga, Mingum. The album was inducted into the Grammy Hall of Fame in 2013.[8]', 'charlesMingus_mingusAhUm_betterGetItInYourSoul.mp3'),
(7, 'charlesMingus_pithecanthropusErectus.png', 'Charles Mingus', 'Pithecanthropus Erectus', '1956', 'Pithecanthropus Erectus is a 1956 album by jazz composer and bassist Charles Mingus. Mingus noted that this was the first album where he taught arrangements to his musicians by ear in lieu of putting the chords and arrangements in writing.[4]', 'charlesMingus_pithecanthropusErectus_aFroggyDay.mp3'),
(8, 'daftPunk_homework.png', 'Daft Punk', 'Homework', '1997', 'Homework is the debut studio album by the French electronic music duo Daft Punk, released on 20 January 1997 by Virgin Records and Soma Quality Recordings. The duo produced the tracks without plans to release an album. After working on projects that were intended to be separate singles over five months, they considered the material good enough for an album.', 'daftPunk_homework_daFunk.mp3'),
(9, 'davidBowie_heroes.png', 'David Bowie', 'Heroes', '1977', '\"Heroes\" is the 12th studio album by English musician David Bowie, released on 14 October 1977 by RCA Records. After releasing Low earlier that year, Bowie toured as the keyboardist of his friend and singer Iggy Pop. At the conclusion of the tour, they recorded Pop\'s second solo album Lust for Life at Hansa Tonstudio in West Berlin before Bowie regrouped there with collaborator Brian Eno and producer Tony Visconti to record \"Heroes\". It was the second instalment of his \"Berlin Trilogy\", following Low and preceding Lodger (1979). Of the three albums, it was the only one wholly recorded in Berlin. Much of the same personnel from Low returned for the sessions, augmented by King Crimson guitarist Robert Fripp.', 'davidBowie_heroes_heroes.mp3'),
(10, 'defLeppard_hysteria.png', 'Def Leppard', 'Hysteria', '1987', 'Hysteria is the fourth studio album by English rock band Def Leppard, released on 3 August 1987 through Mercury Records. It is Def Leppard\'s best-selling album to date, selling over 20 million copies worldwide, including 12 million in the US, and spawning seven hit singles. The album charted at number one on both the Billboard 200 and the UK Albums Chart.[2][3]', 'defLeppard_hysteria_pourSomeSugarOnMe.mp3'),
(11, 'donnaSummer_iRememberYesterday.png', 'Donna Summer', 'I Remember Yesterday', '1977', 'I Remember Yesterday is the fifth studio album by American singer-songwriter Donna Summer. It was released on May 13, 1977, seven months after the release of her previous album. Like her previous three albums, it was a concept album,[1] this time seeing Summer combining the recent disco sound with various sounds of the past. I Remember Yesterday includes the singles \"Can\'t We Just Sit Down (And Talk It Over)\", \"I Feel Love\", the title track, \"Love\'s Unkind\" and \"Back in Love Again\". \"I Feel Love\" and \"Love\'s Unkind\" proved to be the album\'s most popular and enduring hits, the former of which came to be one of Summer\'s signature songs.', 'donnaSummer_iRememberYesterday_iFeelLove.mp3'),
(12, 'fleetwoodMac_rumours.png', 'Fleetwood Mac', 'Rumours', '1977', 'Rumours is the eleventh studio album by British-American rock band Fleetwood Mac, released on 4 February 1977 by Warner Bros. Records. Largely recorded in California in 1976, it was produced by the band with Ken Caillat and Richard Dashut. The band wanted to expand on the commercial success of their eponymous 1975 album, but struggled with relationship breakups before recording started. The Rumours studio sessions were marked by hedonism and strife among band members that shaped the album\'s lyrics.', 'fleetwoodMac_rumours_goYourOwnWay.mp3'),
(13, 'frankSanatra_inTheWeeSmallHours.png', 'Frank Sinatra', 'In The Wee Small Hours', '1955', 'In the Wee Small Hours is the ninth studio album by American vocalist Frank Sinatra. It was released in April 1955 by Capitol and produced by Voyle Gilmore with arrangements by Nelson Riddle. All the songs on the album deal with themes such as loneliness, introspection, lost love, failed relationships, depression, and night life. The cover artwork reflects these themes, portraying Sinatra on an eerie and deserted street at night awash in blue-tinged street lights. In the Wee Small Hours has been called one of the first concept albums.[1][2]', 'frankSanatra_inTheWeeSmallHours_moodIndigo.mp3'),
(14, 'journey_escape.png', 'Journey', 'Escape', '1981', 'Escape (stylized as E5C4P3 on the album cover) is the seventh studio album by American rock band Journey, released in 1981. It topped the American Billboard 200 chart[1] and features four hit Billboard Hot 100 singles – \"Don\'t Stop Believin\'\" (#9), \"Who\'s Crying Now\" (#4), \"Still They Ride\" (#19) and \"Open Arms\" (#2)[2] – plus rock radio staple \"Stone in Love.\" It was certified 9x platinum by the RIAA[3] and sold over twelve million copies worldwide, making it the band\'s most successful studio album and second most successful album overall behind Greatest Hits.', 'journey_escape_don\'tStopBelievin\'.mp3'),
(15, 'massiveAttack_blueLines.png', 'Massive Attack', 'Blue Lines', '1991', 'Blue Lines is the debut studio album by English electronic music group Massive Attack,[a] released on 8 April 1991 by Wild Bunch and Virgin Records.[1] A remastered version of the album was released on 19 November 2012.[2]', 'massiveAttack_blueLines_unfinishedSympathy.mp3'),
(16, 'michaelJackson_thriller.png', 'Michael Jackson', 'Thriller', '1982', 'Thriller is the sixth studio album by American singer Michael Jackson, released on November 30, 1982, by Epic Records. Reunited with Off the Wall producer Quincy Jones, Jackson was inspired to create an album where \"every song was a killer\". With the ongoing backlash against disco, Jackson moved in a new musical direction, incorporating pop, post-disco, rock and funk. Thriller foreshadows the contradictory themes of Jackson\'s personal life, as he began using a motif of paranoia and darker themes. The album features a single guest appearance, with Paul McCartney becoming the first artist to be featured on one of Jackson\'s albums. Recording took place from April to November 1982 at Westlake Recording Studios in Los Angeles, with a production budget of $750,000.', 'michaelJackson_thriller_thriller.mp3'),
(17, 'milesDavis_kindOfBlue.png', 'Miles Davis', 'Kind Of Blue', '1959', 'Kind of Blue is a studio album by American jazz trumpeter-composer Miles Davis. It was recorded on March 2 and April 22, 1959, at Columbia\'s 30th Street Studio in New York City, and released on August 17 of that year by Columbia Records. For the recording, Davis led a sextet featuring saxophonists John Coltrane and Julian \"Cannonball\" Adderley, pianist Bill Evans, bassist Paul Chambers, and drummer Jimmy Cobb, with new band pianist Wynton Kelly appearing on one track in place of Evans.', 'milesDavis_kindOfBlue_soWhat.mp3'),
(18, 'nirvana_nevermind.png', 'Nirvana', 'Nevermind', '1991', 'Nevermind is the second studio album by American rock band Nirvana, released on September 24, 1991 by DGC Records. Produced by Butch Vig, it was Nirvana\'s first release on the DGC label, as well as the first to feature drummer Dave Grohl. Nevermind features a more polished, radio-friendly sound than the band\'s prior work, and is therefore considered a significant departure from their debut album, Bleach. Recording for Nevermind took place at Sound City Studios in Van Nuys, California, and Smart Studios in Madison, Wisconsin in May and June of 1991, with mastering being completed in August of that year at The Mastering Lab in Hollywood, California.', 'nirvana_nevermind_smellsLikeTeenSpirit.mp3'),
(19, 'ornetteColeman_theShapeOfJazz.png', 'Ornette Coleman', 'The Shape Of Jazz To Come', '1959', 'The Shape of Jazz to Come is the third album by jazz musician Ornette Coleman. Released on Atlantic Records in 1959, it was his debut on the label and his first album featuring the working quartet including himself, trumpeter Don Cherry, bassist Charlie Haden, and drummer Billy Higgins.[3] The recording session for the album took place on May 22, 1959, at Radio Recorders in Hollywood, California.[4] Although Coleman initially wished for the album to be titled Focus on Sanity after the LP\'s fourth track, Atlantic producer Nesuhi Ertegun suggested the final title, feeling that it would give consumers \"an idea about the uniqueness of the LP.\"[4]', 'ornetteColeman_theShapeOfJazz_lonelyWoman.mp3'),
(20, 'pjHarvey_ridOfMe.png', 'PJ Harvey', 'Rid Of Me', '1993', 'Rid of Me is the second studio album by English singer-songwriter and musician PJ Harvey. It was released by Island Records in May 1993, approximately one year after the release of her critically acclaimed debut album Dry. It marked a departure from Harvey\'s previous songwriting, being more raw and aggressive than its predecessor.', 'pjHarvey_ridOfMe_ridOfMe.mp3'),
(21, 'portishead_dummy.png', 'Portishead', 'Dummy', '1994', 'Dummy is the debut studio album by English electronic band Portishead, released on 22 August 1994 by Go! Beat Records.[3]The album received critical acclaim and won the 1995 Mercury Music Prize. It is often credited with popularising the trip hop genre, and is frequently cited in lists of the best albums of the 1990s. Dummy was certified triple platinum in the UK in February 2019, for sales of 900,000 copies;[4] and had sold 920,000 copies in the United Kingdom as of September 2020.[5] Worldwide, the album had sold 3.6 million copies by 2008.[6]', 'portishead_dummy_gloryBox.mp3'),
(22, 'ramones_ramones.png', 'Ramones', 'Ramones', '1976', 'Ramones is the debut studio album by American punk rock band Ramones, released on April 23, 1976 by Sire Records. After Hit Parader editor Lisa Robinson saw the band at a gig in New York City, she wrote about them in an article and contacted Danny Fields, insisting that he be their manager. Fields agreed and convinced Craig Leon to produce Ramones, and the band recorded a demo for prospective record labels. Leon persuaded Sire president Seymour Stein to listen to the band perform, and he later offered the band a recording contract. The Ramones began recording in January 1976, needing only seven days and $6,400 to record the album. They used similar sound-output techniques[clarification needed] to those of the Beatles and used advanced production methods by Leon.', 'ramones_ramones_blitzkriegBop.mp3'),
(23, 'samCooke_shake.png', 'Sam Cooke', 'Shake', '1965', 'Shake is the first posthumous studio album by American singer-songwriter Sam Cooke.', 'samCooke_shake_aChangeIsGonnaCome.mp3'),
(24, 'sexPistols_neverMindTheBollocks.png', 'Sex Pistols', 'Never Mind The Bollocks, Here\'s The Sex Pistols', '1977', 'Never Mind the Bollocks, Here\'s the Sex Pistols is the only studio album by English punk rock band the Sex Pistols, released on 28 October 1977 by Virgin Records in the UK and on 11 November 1977 by Warner Bros. in the US. The album has influenced many bands and musicians, and the industry in general. In particular, the album\'s raw energy, and Johnny Rotten\'s sneering delivery and \"half-singing\", are often considered game-changing. It is frequently listed as the most influential punk album, and one of the most important and best albums of all time.', 'sexPistols_neverMindTheBollocks_godSaveTheQueen.mp3'),
(25, 'theB-52\'s_cosmicThing.png', 'The B-52\'s', 'Cosmic Thing', '1989', 'Cosmic Thing is the fifth studio album by American new wave band the B-52\'s, released in 1989. It contains the singles \"Love Shack\" and \"Roam\". The success of the album served as a comeback after the death of guitarist Ricky Wilson in 1985.', 'theB-52\'s_cosmicThing_loveShack.mp3'),
(26, 'theBeachBoys_petSounds.png', 'The Beach Boys', 'Pet Sounds', '1966', 'Pet Sounds is the 11th studio album by the American rock band the Beach Boys, released May 16, 1966 on Capitol Records. It was initially met with a lukewarm critical and commercial response in the United States, peaking at number 10 on Billboard Top LPs chart, lower than the band\'s preceding albums. In the United Kingdom, the album was favorably received by critics and peaked at number 2 in the UK Top 40 Albums Chart, remaining in the top ten for six months. Promoted there as \"the most progressive pop album ever\", Pet Sounds attracted recognition for its ambitious production, sophisticated music, and emotional lyric content. It is considered to be among the most influential albums in music history.[1]', 'theBeachBoys_petSounds_godOnlyKnows.mp3'),
(27, 'theBeatles_sgt.Peppers.png', 'The Beatles', 'Sgt.Pepper\'s Lonely Hearts Club Band', '1967', 'Sgt. Pepper\'s Lonely Hearts Club Band is the eighth studio album by the English rock band the Beatles. Released on 26 May 1967,[nb 1] it spent 27 weeks at number one on the Record Retailer chart in the United Kingdom and 15 weeks at number one on the Billboard Top LPs chart in the United States. It was lauded by critics for its innovations in songwriting, production and graphic design, for bridging a cultural divide between popular music and high art, and for reflecting the interests of contemporary youth and the counterculture. Its release was a defining moment in 1960s pop culture, heralding the Summer of Love, while the album\'s reception achieved full cultural legitimisation for pop music and recognition for the medium as a genuine art form.', 'theBeatles_sgt.Peppers_aDayInTheLife.mp3'),
(28, 'theClash_theClash.png', 'The Clash', 'The Clash', '1977', 'The Clash is the self-titled debut studio album by English punk rock band the Clash. It was released on 8 April 1977 through CBS Records. Written and recorded over three weeks in February 1977 for £4,000, it would go on to reach No. 12 on the UK charts, and has been included on many retrospective rankings as one of the greatest punk albums of all time.', 'theClash_theClash_londonCalling.mp3'),
(29, 'theJacksonFive_iWantYouBack.png', 'The Jackson Five', 'I Want You Back', '1969', '\"I Want You Back\" is the first national single by the Jackson 5.[3] It was released by Motown on October 7, 1969, and became the first number-one hit for the band on January 31, 1970.[4] It was performed on the band\'s first television appearances, on October 18, 1969 on Diana Ross\'s The Hollywood Palace and on their milestone performance on December 14, 1969 on The Ed Sullivan Show.[4]', 'theJacksonFive_iWantYouBack.mp3'),
(30, 'theRonettes_presentingTheFabulous.png', 'The Ronettes', 'Presenting The Fabulous Ronettes Featuring Veronica', '1964', 'Presenting the Fabulous Ronettes Featuring Veronica is the only studio album of American girl group the Ronettes, released in 1964. Comprising numerous singles produced by Phil Spector since the previous year, it peaked at #96 on the Billboard 200 chart. Issued singles included \"Be My Baby\" (US #2), \"Walking in the Rain\" (US #23), \"Baby, I Love You\" (US #24), \"Do I Love You?\" (US #34), and \"(The Best Part Of) Breakin\' Up\" (US #39). The track \"So Young\" had been released as a single credited to Veronica, although the other Ronettes, Estelle Bennett and Nedra Talley, appear on the record.', 'theRonettes_presentingTheFabulous_beMyBaby.mp3'),
(31, 'tlc_crazySexyCool.png', 'TLC', 'Crazy Sexy Cool', '1994', 'CrazySexyCool is the second studio album by American girl group TLC. It was released on November 15, 1994, by LaFace and Arista Records. Following the group\'s record deal, they released their debut album Ooooooohhh... On the TLC Tip in 1992 to positive reviews and commercial success. The following year the group began working on a follow-up with an unproductive recording process due to personal struggles, notably those of member Lisa \"Left Eye\" Lopes who was involved in a volatile romantic relationship and struggling with alcoholism. The album\'s recording lasted until September 1994, with Lopes\' role diminished because she was in rehab.', 'tlc_crazySexyCool_waterfalls.mp3');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_tv`
--

DROP TABLE IF EXISTS `tbl_tv`;
CREATE TABLE IF NOT EXISTS `tbl_tv` (
  `tv_id` int(11) NOT NULL AUTO_INCREMENT,
  `tv_cover` varchar(50) NOT NULL,
  `tv_title` varchar(50) NOT NULL,
  `tv_year` varchar(12) NOT NULL,
  `tv_storyline` text NOT NULL,
  `tv_video` varchar(50) NOT NULL,
  PRIMARY KEY (`tv_id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_tv`
--

INSERT INTO `tbl_tv` (`tv_id`, `tv_cover`, `tv_title`, `tv_year`, `tv_storyline`, `tv_video`) VALUES
(1, 'andyGriffithShow.png', 'The Andy Griffith Show', '1960', 'The series plot revolves around Sheriff Andy Taylor (Andy Griffith) and his life in sleepy, slow-paced fictional Mayberry, North Carolina. Sheriff Taylor\'s level-headed approach to law enforcement makes him the scourge of local moonshiners and out-of-town criminals, while his abilities to settle community problems with common-sense advice, mediation, and conciliation make him popular with his fellow citizens. His professional life, however, is complicated by the repeated gaffes of his inept deputy, Barney Fife (Don Knotts). Barney is Andy\'s cousin, but that is only mentioned in a few early episodes. Andy socializes with male friends in the Main Street barbershop and dates various ladies until a schoolteacher becomes his steady interest in season three. At home, Andy enjoys fishing trips with his son, Opie (Ronny Howard), and quiet evenings on the front porch with his maiden aunt and housekeeper, Aunt Bee (Frances Bavier). Opie tests his father\'s parenting skills season after season, and Aunt Bee\'s ill-considered romances and adventures cause her nephew concern.[citation needed] Andy\'s friends and neighbors include, at various times, barber Floyd Lawson (Howard McNear; Walter Baldwin portrayed the role in the 1960 episode \"Stranger in Town\"), service station attendants and cousins Gomer Pyle (Jim Nabors) and Goober Pyle (George Lindsey), and local drunkard Otis Campbell (Hal Smith). There were two mayors: Mayor Pike (Richard Damon Elliott), who was more relaxed and often indecisive, and Mayor Roy Stoner (Parley Baer) who had a more assertive personality. On the distaff side, townswoman Clara Edwards (Hope Summers), Barney\'s sweetheart Thelma Lou (Betty Lynn) and Andy\'s schoolteacher sweetheart Helen Crump (Aneta Corsaut) become semi-regulars. Ellie Walker (Elinor Donahue) is Andy\'s girlfriend in the first season, while Peggy McMillan (Joanna Moore) is a nurse who becomes his girlfriend in season 3. Ernest T. Bass made his first appearance in Episode #94 (\"Mountain Wedding\") and four later episodes. The actor who portrayed him, Howard Morris, also appeared as George, the television repairman, in Episode #140 (\"Andy and Helen Have Their Day\") and in two, uncredited voice roles as Leonard Blush and a radio announcer. ', 'andyGriffith.mp4'),
(4, 'freshPrince.png', 'The Fresh Prince Of Bel-Air', '1990', 'The theme song and opening sequence set the premise of the show. Will Smith is a street-smart teenager, West Philadelphia \"born and raised\". While playing street basketball, Will misses a shot and the ball hits a group of gang members, causing a confrontation that frightens his mother, who sends him to live with his wealthy aunt and uncle in the opulent neighborhood of Bel Air, Los Angeles.', 'freshPrince.mp4'),
(5, 'friends.png', 'Friends', '1994', 'Rachel Green, a sheltered but friendly woman, flees her wedding day and wealthy yet unfulfilling life and finds childhood friend Monica Geller, a tightly wound but caring chef. After Rachel becomes a waitress at West Village coffee house Central Perk, she moves into Monica\'s apartment above Central Perk and joins Monica\'s group of single friends in their mid-20s: previous roommate Phoebe Buffay, an eccentric, weird masseuse; neighbor Joey Tribbiani, a dim-witted yet loyal struggling actor and womanizer; Joey\'s roommate Chandler Bing, a sarcastic, self-deprecating IT manager; and Monica\'s older brother and Chandler\'s college roommate Ross Geller, a sweet-natured but insecure paleontologist.', 'friends.mp4'),
(2, 'carolBurnett.png', 'The Carol Burnett Show', '1977', 'The Carol Burnett Show is an American variety/sketch comedy television show starring Carol Burnett, Harvey Korman, Vicki Lawrence, and Lyle Waggoner. In 1975, frequent guest star Tim Conway became a regular after Waggoner left the series.[2] In 1977, Dick Van Dyke replaced Korman but it was agreed that it was not a match and he left after 10 episodes.[3]', 'carolBurnett.mp4'),
(3, 'cheers.png', 'Cheers', '1982', 'Cheers is an American sitcom television series that ran on NBC from September 30, 1982, to May 20, 1993, with a total of 275 half-hour episodes across eleven seasons. The show was produced by Charles/Burrows Productions in association with Paramount Network Television, and was created by the team of James Burrows and Glen and Les Charles. The show is set in a bar named Cheers Beacon Hill in Boston, Massachusetts, where a group of locals meet to drink, relax, and socialize. The show\'s main theme song, co-written and performed by Gary Portnoy, lent its refrain \"Where Everybody Knows Your Name\" as the show\'s catchphrase.[2]', 'cheers.mp4'),
(6, 'giligansIsland.png', 'Giligans Island', '1964', 'The two-man crew of the charter boat SS Minnow and five passengers on a \"three-hour tour\" from Honolulu run into a typhoon and are shipwrecked on an uncharted island somewhere in the Pacific Ocean. Their efforts to be rescued are typically thwarted by the inadvertent conduct of the hapless first mate, Gilligan. In 1997, show creator Sherwood Schwartz explained that the underlying concept is still \"the most important idea in the world today\".[2] That is, people with extremely different characters and backgrounds being in a situation where they need to learn how to get along and cooperate with each other as a matter of survival.', 'giligansIsland.mp4'),
(7, 'happyDays.png', 'Happy Days', '1974', 'Set in Milwaukee, Wisconsin, the series revolves around teenager Richie Cunningham and his family: his father, Howard, who owns a hardware store; traditional homemaker and mother, Marion; younger sister Joanie Cunningham; Richie\'s older brother Chuck (briefly in seasons 1 and 2 only, disappearing from storylines afterward); and high school dropout, greaser, and suave ladies\' man Fonzie, who would eventually become Richie\'s best friend and the Cunninghams\' over-the-garage tenant. The earlier episodes revolve around Richie and his friends, Potsie Weber and Ralph Malph, with Fonzie as a secondary character. However, as the series progressed, Fonzie proved to be a favorite with viewers, and soon more story lines were written to reflect his growing popularity; Winkler eventually received top billing in the opening credits alongside Howard.[5] Fonzie befriended Richie and the Cunningham family, and when Richie left the series for military service, Fonzie became the central figure of the show, with Winkler receiving sole top billing. In later seasons, other characters were introduced including Fonzie\'s young cousin, Chachi Arcola, who became a love interest for Joanie Cunningham. The 11 seasons of the series roughly track the 11 years from 1955 to 1965 in which the show was set.', 'happyDays.mp4'),
(8, 'homeImprovement.png', 'Home Improvement', '1991', 'The series centers on the Taylor family, which consists of Tim (Tim Allen), his wife Jill (Patricia Richardson) and their three children: the oldest child, Brad (Zachery Ty Bryan), the middle child, Randy (Jonathan Taylor Thomas) and youngest child, Mark (Taran Noah Smith). The Taylors live in suburban Detroit, and have a neighbor named Wilson (Earl Hindman) who is often the go-to guy for solving the Taylors\' problems.', 'homeImprovement.mp4'),
(9, 'iLoveLucy.png', 'I Love Lucy', '1951', 'Originally set in an apartment building in New York City, I Love Lucy centers on Lucy Ricardo (Lucille Ball) and her singer/bandleader husband Ricky Ricardo (Desi Arnaz), along with their best friends and landlords Fred Mertz (William Frawley) and Ethel Mertz (Vivian Vance). During the second season, Lucy and Ricky have a son named Ricky Ricardo Jr. (\"Little Ricky\"), whose birth was timed to coincide with Ball\'s real-life birth of her son Desi Arnaz Jr.[10]', 'iLoveLucy.mp4'),
(10, 'knightRider.png', 'Knight Rider', '1982', 'Self-made billionaire Wilton Knight rescues police Detective Lieutenant Michael Arthur Long after a near fatal shot to the face, giving him a new identity (by plastic surgery) and a new name: Michael Knight. Wilton selects Michael to be the primary field agent in the pilot program of his public justice organization, the Foundation for Law and Government (FLAG). The other half of this pilot program is the Knight Industries Two Thousand (KITT), a heavily modified, technologically advanced Pontiac Firebird Trans Am with numerous features, including an extremely durable shell and frame, controlled by a computer with artificial intelligence. Michael and KITT are brought in during situations where \"direct action might provide the only feasible solution\".', 'knightRider.mp4'),
(11, 'leaveBeaver.png', 'Leave It To Beaver', '1957', 'In 1957, the radio, film and television writers Joe Connelly and Bob Mosher developed a concept for a TV show about childhood and family life featuring a fictional suburban couple and their children. Unlike The Adventures of Ozzie & Harriet, Father Knows Best and other sitcoms and domestic comedies of the era, the show would not focus on the parents, but rather on their children, with the series being told from the kids\' point of view.[5] Working titles during the show\'s gestation period included It\'s a Small World[2] and Wally and the Beaver. The pilot aired April 23, 1957, as \"It\'s a Small World\" on the anthology series Heinz Studio 57.[3]', 'leaveBeaver.mp4'),
(12, 'looneyTunes.png', 'Looney Tunes', '1930', 'More popular Looney Tunes characters were created (most of which first appeared in Merrie Melodies cartoons) such as Tweety (debuted in 1942\'s A Tale of Two Kitties), Sylvester (debuted in 1945\'s Life with Feathers), Yosemite Sam (debuted in 1945\'s Hare Trigger), Pepé Le Pew (debuted in 1945\'s Odor-able Kitty), Foghorn Leghorn (debuted in 1946\'s Walky Talky Hawky), Marvin the Martian (debuted in 1948\'s Haredevil Hare), Wile E. Coyote and the Road Runner (debuted in 1949\'s Fast and Furry-ous), Granny (debuted in 1950\'s Canary Row), Speedy Gonzales (debuted in 1953\'s Cat Tails for Two), Witch Hazel (debuted in 1954\'s Bewitched Bunny), and the Tasmanian Devil (debuted in 1954\'s Devil May Hare).', 'looneyTunes.mp4'),
(13, 'magnumPI.png', 'Magnum P.I.', '1980', 'Thomas Sullivan Magnum IV is a private investigator played by Tom Selleck. He lives in the guest house of a 200-acre (81 ha) beachfront estate called Robin\'s Nest, in Hawaii, at the invitation of its owner, Robin Masters, the celebrated, unseen character, author of several dozen lurid novels. Ostensibly this is quid pro quo for Magnum\'s services based upon his expertise in security; the pilot and several early episodes suggest Magnum had done Masters a favor of some kind, possibly when Masters hired him for a case. The voice of Robin Masters, heard only in five episodes, was provided by Orson Welles (one last appearance was provided by a different actor, Red Crandell).[4]', 'magnumPI.mp4'),
(14, 'mash.png', 'M*A*S*H', '1972', 'M*A*S*H, a TV adaptation of the film, ran from 1972 to 1983, more than three times as long as the war it chronicled. It starred Alan Alda as Hawkeye Pierce and Wayne Rogers as Trapper John McIntyre. After the third season, Rogers left the show and was replaced by Mike Farrell as B. J. Hunnicutt. That same year, Harry Morgan replaced McLean Stevenson. Morgan, a veteran character actor and former Universal contract player, portrayed Colonel Sherman T. Potter. This series is the most popular and best-known version of the franchise and was ranked #25 in TV Guide\'s \"50 Greatest TV Shows of All Time\". Its final episode in 1983 was the most-watched in television history.[2]', 'mashIntro.mp4'),
(15, 'macGyver.png', 'MacGyver', '1985', 'The show follows secret agent Angus MacGyver, played by Richard Dean Anderson, who works as a troubleshooter for the fictional Phoenix Foundation in Los Angeles and as an agent for a fictional United States government agency, the Department of External Services (DXS). Educated as a scientist in Physics at Western Tech (\"Hell Week\"), MacGyver served in the U.S. Army Special Forces as a Bomb Team Technician/EOD during the Vietnam War (\"Countdown\"). Resourceful and possessing an encyclopedic knowledge of the physical sciences, he solves complex problems by making things out of ordinary objects, along with his ever-present Swiss Army knife, duct tape, and occasionally matches. He favors non-violent resolutions and prefers not to handle firearms due to the accidental shooting death of one of his friends when he was 12.', 'mcGyver.mp4'),
(16, 'rockfordFiles.png', 'The Rockford Files', '1974', 'Producers Roy Huggins and Stephen J. Cannell devised the Rockford character as a rather significant departure from typical television detectives of the time, essentially Bret Maverick as a modern detective.[2] In the series storyline, Jim Rockford had served time in California\'s San Quentin Prison in the 1960s due to a wrongful conviction. After five years, he was pardoned (not paroled, a distinction frequently mentioned in plot points). His infrequent jobs as a private investigator barely allow him to maintain his dilapidated mobile home (which doubles as his office) in a parking lot on a beach in Malibu, California.', 'rockfordFiles.mp4'),
(17, 'simpsons.png', 'The Simpsons', '1989', 'The main characters are the Simpson family, who live in a fictional \"Middle America\" town of Springfield.[10] Homer, the father, works as a safety inspector at the Springfield Nuclear Power Plant, a position at odds with his careless, buffoonish personality. He is married to Marge Bouvier, a stereotypical American housewife and mother. They have three children: Bart, a ten-year-old troublemaker and prankster; Lisa, a precocious eight-year-old activist; and Maggie, the baby of the family who rarely speaks, but communicates by sucking on a pacifier. Although the family is dysfunctional, many episodes examine their relationships and bonds with each other and they are often shown to care about one another.[11] Homer\'s dad Grampa Simpson lives in the Springfield Retirement Home after Homer forced his dad to sell his house so that his family could buy theirs. Grampa Simpson has had starring roles in several episodes.', 'simpsons.mp4'),
(18, 'starTrek.png', 'Star Trek', '1968', 'The series was produced from September 1966 to December 1967 by Norway Productions and Desilu Productions, and by Paramount Television from January 1968 to June 1969. Star Trek aired on NBC from September 8, 1966, to June 3, 1969,[6] and was actually seen first on September 6, 1966, on Canada\'s CTV network.[7] Star Trek\'s Nielsen ratings while on NBC were low, and the network cancelled it after three seasons and 79 episodes. Several years later, the series became a hit in broadcast syndication, remaining so throughout the 1970s, achieving cult classic status and a developing influence on popular culture. Star Trek eventually spawned a franchise, consisting of eight television series, 13 feature films, and numerous books, games, and toys, and is now widely considered one of the most popular and influential television series of all time.[8] The series contains significant elements of Space Western, as described by Roddenberry and the general audience.[9]', 'starTrek.mp4'),
(19, 'theFlintstones.png', 'The Flintstones', '1960', 'The show is set in a comical version of the Stone Age, but has added features and technologies that resemble mid-20th-century suburban America. The plots deliberately resemble the sitcoms of the era, with the caveman Flintstone and Rubble families getting into minor conflicts characteristic of modern life.[7] The show is set in the Stone Age town of Bedrock (pop. 2,500). Dinosaurs and other prehistoric creatures are portrayed to co-exist during the time of cavemen, saber-toothed cats, and woolly mammoths.', 'theFlintstones.mp4'),
(20, 'twilight.png', 'The Twilight Zone', '1959', 'The Twilight Zone is an American media franchise based on the anthology television series created by Rod Serling. The episodes are in various genres, including fantasy, science fiction, absurdism, dystopian fiction, suspense, horror, supernatural drama, black comedy, and psychological thriller, often concluding with a macabre or unexpected twist, and usually with a moral. A popular and critical success, it introduced many Americans to common science fiction and fantasy tropes. The first series, shot entirely in black and white, ran on CBS for five seasons from 1959 to 1964.', 'twilightZone.mp4');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_user`
--

DROP TABLE IF EXISTS `tbl_user`;
CREATE TABLE IF NOT EXISTS `tbl_user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(50) NOT NULL,
  `user_pass` varchar(50) NOT NULL,
  `user_access` int(5) NOT NULL,
  `user_avatar` varchar(50) NOT NULL,
  `user_age` varchar(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_user`
--

INSERT INTO `tbl_user` (`user_id`, `user_name`, `user_pass`, `user_access`, `user_avatar`, `user_age`) VALUES
(1, 'user1', 'pass', 5, 'test_avatar1.png', '0'),
(2, 'RegProfile', 'pass', 5, 'test_avatar2.png', '0'),
(3, 'KidProfile', 'pass', 1, 'test_avatar3.png', '1');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
